spring:
  thymeleaf:
    cache: false
    prefix: "classpath:/templates/"
    suffix: .html
  redis:
    host: 192.168.184.132

sso:
  server:
    url: http://ssoserver.com:8080/login.html
server:
  port: 81